// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#r "Microsoft.Build.Conversion.v4.0.dll"
#r "Microsoft.Build.dll"
#r "Microsoft.Build.Engine.dll"
#r "Microsoft.Build.Framework.dll"
#r "Microsoft.Build.Tasks.v4.0.dll"
#r "Microsoft.Build.Utilities.v4.0.dll"
#r "PresentationBuildTasks.dll"
#r "System.Core.dll"
#r "System.Data.dll"
#r "System.dll"
#r "System.Numerics.dll"
#r "System.Xaml.dll"
#r "System.Xml.dll"
#r "System.Xml.Linq.dll"
#r "XamlBuildTask.dll"